import { mainColors } from "#/Layout";
import { useMemo, useState } from "react";

export interface Module {
  name: string;
  title?: string;
  url: string;
  showInMenu: boolean;
  hasLayout: boolean;
  hasNavigation?: boolean;
  hasTopBar?: boolean;
  themeColor: string;
  parent?: string;
}

export const MODULES: Module[] = [
  {
    name: "home",
    url: "/home",
    title: "خانه",
    showInMenu: true,
    hasLayout: true,
    themeColor: mainColors.blue,
  },
  {
    name: "market",
    url: "/market",
    title: "مارکت",
    showInMenu: true,
    hasLayout: true,
    themeColor: mainColors.green,
  },
  {
    name: "marketCart",
    url: "/market/cart",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketCartCheckout",
    url: "/market/cart/checkout",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketCartDetails",
    url: "/market/cart/details",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketCategories",
    url: "/market/categories",
    showInMenu: false,
    hasLayout: true,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketAllStores",
    url: "/market/allStores",
    showInMenu: false,
    hasLayout: true,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketStore",
    url: "/market/allStores/store",
    showInMenu: false,
    hasLayout: true,
    hasNavigation: false,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketAllProducts",
    url: "/market/allProducts",
    showInMenu: false,
    hasLayout: true,
    hasNavigation: false,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "marketProduct",
    url: "/market/allProducts/product",
    showInMenu: false,
    hasLayout: true,
    hasNavigation: false,
    themeColor: mainColors.green,
    parent: "market",
  },
  {
    name: "post",
    url: "/post",
    title: "پیک",
    showInMenu: true,
    hasLayout: true,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postSourcePrimary",
    url: "/post",
    showInMenu: false,
    hasLayout: true,
    themeColor: mainColors.brightBlue,
    parent: "post",
  },
  {
    name: "postSourceSecondary",
    url: "/post",
    showInMenu: false,
    hasLayout: true,
    hasNavigation: false,
    themeColor: mainColors.brightBlue,
    parent: "post",
  },
  {
    name: "postDestinationPrimary",
    url: "/post",
    showInMenu: false,
    hasLayout: true,
    themeColor: mainColors.brightBlue,
    parent: "post",
  },
  {
    name: "postDestinationSecondary",
    url: "/post",
    showInMenu: false,
    hasLayout: true,
    hasNavigation: false,
    themeColor: mainColors.brightBlue,
    parent: "post",
  },
  {
    name: "postSearching",
    url: "/post/searching",
    showInMenu: false,
    hasLayout: true,
    themeColor: mainColors.brightBlue,
    parent: "post",
    hasTopBar: false,
  },
  {
    name: "postOrders",
    url: "/post/orders",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postDelivery",
    url: "/post/delivery",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postDiscount",
    url: "/post/discount",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postLocation",
    url: "/post/location",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postTracking",
    url: "/post/tracking",
    showInMenu: false,
    hasLayout: true,
    parent: "post",
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postCanceling",
    url: "/post/canceling",
    showInMenu: false,
    hasLayout: false,
    parent: "post",
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postDeliveryDelay",
    url: "/post/delivery/delay",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postDeliveryReserve",
    url: "/post/delivery/reserve",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "postDeliveryCheckout",
    url: "/post/delivery/checkout",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.brightBlue,
  },
  {
    name: "auth",
    url: "/auth",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.blue,
  },
  {
    name: "authVerify",
    url: "/auth/verify",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.blue,
  },
  {
    name: "authSignUp",
    url: "/auth/signUp",
    showInMenu: false,
    hasLayout: false,
    themeColor: mainColors.blue,
  },
];
